version: '3.3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    depends_on:
      - db
    volumes:
      - ./backend:/code
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    restart: on-failure
    env_file:
      - ./.env.prod

  db:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.proddb
    ports:
      - 5432:5432

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./backend/static/:/code/static/
      - ./nginx/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/totrno.com/fullchain.pem:/etc/letsencrypt/live/totrno.com/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/totrno.com/privkey.pem:/etc/letsencrypt/live/totrno.com/privkey.pem


volumes:
  postgres_data: {}
